// ─────────────────────────────────────────────
//  HackerDeck — APK Store Catalogue
// ─────────────────────────────────────────────
import 'package:hackerdeck/models.dart';

List<StoreApp> buildStoreApps() => [
      StoreApp(
        name: 'F-Droid',
        category: 'Store',
        description: 'Otwarty sklep z aplikacjami open-source',
        icon: '📦',
        downloadUrl: 'https://f-droid.org/F-Droid.apk',
        version: '1.20',
      ),
      StoreApp(
        name: 'Aurora Store',
        category: 'Store',
        description: 'Klient Google Play bez konta Google',
        icon: '🌌',
        downloadUrl: 'https://auroraoss.com/downloads/AuroraStore/Stable/',
        version: '4.4.3',
      ),
      StoreApp(
        name: 'VLC Media Player',
        category: 'Media',
        description: 'Odtwarzacz multimedialny',
        icon: '🎬',
        downloadUrl: 'https://get.videolan.org/vlc-android/3.6.0/VLC-Android-3.6.0.apk',
        version: '3.6.0',
      ),
      StoreApp(
        name: 'Termux',
        category: 'Narzędzia',
        description: 'Terminal z apt dla Androida',
        icon: '💻',
        downloadUrl: 'https://f-droid.org/repo/com.termux_118.apk',
        version: '0.118',
      ),
      StoreApp(
        name: 'Kodi',
        category: 'Media',
        description: 'Centrum mediów domowych',
        icon: '📺',
        downloadUrl: 'https://mirrors.kodi.tv/releases/android/arm64-v8a/kodi-21.0-Omega-arm64-v8a.apk',
        version: '21.0',
      ),
      StoreApp(
        name: 'NewPipe',
        category: 'Media',
        description: 'YouTube bez reklam i śledzenia',
        icon: '▶️',
        downloadUrl: 'https://github.com/TeamNewPipe/NewPipe/releases/latest',
        version: '0.27.2',
      ),
      StoreApp(
        name: 'Brave Browser',
        category: 'Przeglądarka',
        description: 'Szybka przeglądarka z blokadą reklam',
        icon: '🦁',
        downloadUrl: 'https://github.com/brave/brave-browser/releases/latest',
        version: '1.69',
      ),
      StoreApp(
        name: 'LibreOffice Viewer',
        category: 'Biuro',
        description: 'Przeglądarka .odt .docx .xlsx',
        icon: '📄',
        downloadUrl: 'https://www.libreoffice.org/download/android-viewer/',
        version: '24.8',
      ),
      StoreApp(
        name: 'OsmAnd',
        category: 'Mapy',
        description: 'Mapy offline OpenStreetMap',
        icon: '🗺️',
        downloadUrl: 'https://osmand.net/uploads/apps/net.osmand-4.8.5.apk',
        version: '4.8.5',
      ),
      StoreApp(
        name: 'Nextcloud',
        category: 'Chmura',
        description: 'Klient prywatnej chmury',
        icon: '☁️',
        downloadUrl: 'https://github.com/nextcloud/android/releases/latest',
        version: '3.30',
      ),
      StoreApp(
        name: 'Signal',
        category: 'Komunikacja',
        description: 'Szyfrowany komunikator',
        icon: '🔒',
        downloadUrl: 'https://signal.org/android/apk/',
        version: '7.22',
      ),
      StoreApp(
        name: 'KeePassDX',
        category: 'Bezpieczeństwo',
        description: 'Menedżer haseł open-source',
        icon: '🔑',
        downloadUrl: 'https://github.com/Kunzisoft/KeePassDX/releases/latest',
        version: '4.0.9',
      ),
      StoreApp(
        name: 'Obsidian',
        category: 'Notatki',
        description: 'Notatki Markdown z grafem powiązań',
        icon: '💎',
        downloadUrl: 'https://github.com/obsidianmd/obsidian-releases/releases/latest',
        version: '1.7.4',
      ),
      StoreApp(
        name: 'PPSSPP',
        category: 'Emulacja',
        description: 'Emulator PSP',
        icon: '🎮',
        downloadUrl: 'https://www.ppsspp.org/downloads.html',
        version: '1.17.1',
      ),
      StoreApp(
        name: 'RetroArch',
        category: 'Emulacja',
        description: 'Emulator wielu platform retro',
        icon: '🕹️',
        downloadUrl: 'https://www.retroarch.com/?page=platforms',
        version: '1.19',
      ),
    ];
